using System;

namespace SpaceStation.Enums
{
	public enum PredefParticleMaterial
	{
		PREDEF_MATERIAL_DEFAULT_BLOCK,
		PREDEF_MATERIAL_DEFAULT_CIRCLE,
		PREDEF_MATERIAL_DEFAULT_LIGHT_RAIN,
		PREDEF_MATERIAL_DEFAULT_HEAVY_RAIN,
		PREDEF_MATERIAL_DEFAULT_FEINT_SMOKE,
		PREDEF_MATERIAL_DEFAULT_MEDIUM_SMOKE,
		PREDEF_MATERIAL_DEFAULT_THICK_SMOKE,
		PREDEF_MATERIAL_DEFAULT_KINDLE_FIRE,
		PREDEF_MATERIAL_DEFAULT_COOKING_FIRE
	}
}
